# ci_scripts/Dockerfile.luxonis_underlay
FROM intrinsic-dev-core-underlay:latest AS underlay

RUN apt-get update \
    && apt-get install -y \
        build-essential \
        ninja-build \
        ca-certificates \
        xz-utils \
    && rm -rf /var/lib/apt/lists/*

ADD src/depthai-core /opt/ros/underlay/src/depthai-core
ADD src/depthai-ros /opt/ros/underlay/src/depthai-ros

# TODO remove this once the maintainer tag is added to the package.xml in the depthai-core repo
RUN sed -i '/<\/license>/a \  <maintainer email="support@luxonis.com">Luxonis Support</maintainer>' \
    /opt/ros/underlay/src/depthai-core/package.xml

# Compile the Luxonis SDKs into the underlay
RUN . /opt/ros/jazzy/setup.sh \
    && cd /opt/ros/underlay \
    && colcon build \
      --event-handlers=console_direct+ \
      --merge-install \
      --executor sequential \
      --cmake-args -DBUILD_SHARED_LIBS=ON -DDEPTHAI_BOOTSTRAP_VCPKG=ON \
    && rm -rf /opt/ros/underlay/build /opt/ros/underlay/log /opt/ros/underlay/src /root/.cache
