# Dockerfile.zivid_underlay
FROM nvidia/cuda:12.5.1-base-ubuntu24.04 AS base

ARG ZIVID_VERSION=2.17.0+5fc9f05e-1

# Install ROS Jazzy TODO REMOVE
RUN apt-get update && apt-get install -y curl gnupg2 lsb-release && rm -rf /var/lib/apt/lists/*
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
RUN apt-get clean && apt-get update && apt-get install -y --fix-missing ros-jazzy-ros-base && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/ros/underlay
ENV ROS_DISTRO=jazzy
ENV ROS_HOME=/tmp
ENV RMW_IMPLEMENTATION=rmw_zenoh_cpp

RUN mkdir -p /etc/OpenCL/vendors && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
COPY --from=ghcr.io/intrinsic-dev/core-underlay:latest /opt/ros/underlay/install /opt/ros/underlay/install

RUN apt-get update && apt-get install -y wget && \
    wget https://downloads.zivid.com/sdk/releases/${ZIVID_VERSION}/u24/amd64/zivid_${ZIVID_VERSION}_amd64.deb \
         https://downloads.zivid.com/sdk/releases/${ZIVID_VERSION}/u24/amd64/zivid-studio_${ZIVID_VERSION}_amd64.deb \
         https://downloads.zivid.com/sdk/releases/${ZIVID_VERSION}/u24/amd64/zivid-tools_${ZIVID_VERSION}_amd64.deb \
         https://downloads.zivid.com/sdk/releases/${ZIVID_VERSION}/u24/amd64/zivid-genicam_${ZIVID_VERSION}_amd64.deb && \
    apt-get install -y ./*.deb && rm ./*.deb && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

RUN apt-get update \
    && apt-get install -y \
        build-essential \
        python3-colcon-common-extensions \
        ros-dev-tools \
        ros-jazzy-ament-cmake-vendor-package \
        ros-jazzy-cv-bridge \
        ros-jazzy-image-transport \
        ros-jazzy-image-transport-plugins \
        ros-jazzy-camera-info-manager \
        ros-jazzy-diagnostic-updater \
        ros-jazzy-sensor-msgs \
        ros-jazzy-geometry-msgs \
        ros-jazzy-std-srvs \
        python3-protobuf \
        libopencv-dev \
        nlohmann-json3-dev \
        libzmq3-dev \
        cppzmq-dev \
        libbz2-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

ADD src/zivid-ros /opt/ros/underlay/src/zivid-ros

# Compile the Zivid ROS wrapper into the underlay
RUN . /opt/ros/jazzy/setup.sh \
    && cd /opt/ros/underlay \
    && colcon build \
      --merge-install \
      --executor sequential \
      --packages-skip zivid_rviz_plugin
      --cmake-args -DCMAKE_BUILD_TYPE=Release \
    && rm -rf /opt/ros/underlay/build /opt/ros/underlay/log /opt/ros/underlay/src /root/.cache
