# ci_scripts/Dockerfile.core_underlay
FROM ros:jazzy-ros-core AS underlay

WORKDIR /opt/ros/underlay
ENV ROS_DISTRO=jazzy
ENV ROS_HOME=/tmp
ENV RMW_IMPLEMENTATION=rmw_zenoh_cpp

# Install build tool and common dependencies for all underlays
RUN apt-get update && apt install -y \
    clang ros-jazzy-ament-cmake-vendor-package ros-dev-tools git wget \
    python3-protobuf \
    libopencv-dev \
    nlohmann-json3-dev \
    ros-jazzy-tf2-ros \
    ros-jazzy-tf2-geometry-msgs \
    libgl1-mesa-dev \
    ros-jazzy-cv-bridge \
    ros-jazzy-backward-ros \
    ros-jazzy-camera-info-manager \
    ros-jazzy-image-transport \
    ros-jazzy-image-publisher \
    ros-jazzy-tf2-eigen \
    ros-jazzy-tf2-sensor-msgs \
    ros-jazzy-diagnostic-updater \
    curl zip unzip tar libusb-1.0-0-dev \
    ros-jazzy-vision-msgs \
    ros-jazzy-ffmpeg-image-transport-msgs \
    && rm -rf /var/lib/apt/lists/*

# Skip these packages in downstream service wrapper builds to save time
ENV COMMON_SKIP_PACKAGES="intrinsic_sdk intrinsic_sdk_ros intrinsic_sdk_cmake gz_msgs_vendor grpc_vendor abseil_cpp_vendor re2_vendor rmw_zenoh_cpp ortools_vendor eigen_vendor gz_make_vendor gz_utils_vendor intrinsic_pybind11_vendor gz_math_vendor prometheus_cpp_vendor bazelisk_vendor flatbuffers_vendor opencensus_cpp_vendor pybind11_abseil_vendor pybind11_protobuf_vendor gz_cmake_vendor gz_transport_vendor"

RUN rosdep init && rosdep update

# Add the shared heavy source code
ADD src/sdk-ros /opt/ros/underlay/src/intrinsic_sdk_ros

# Install the custom rmw_zenoh fork
RUN cd /opt/ros/underlay/src/ \
    && git clone https://github.com/codebot/rmw_zenoh -b morganquigley/jazzy_with_old_attachment_metadata_format \
    && cd rmw_zenoh && git checkout 05cdda05a7c5e7c2871e6d85bfc9411546a529c4

# Install rosdep dependencies for these core packages
RUN apt-get update \
    && . /opt/ros/jazzy/setup.sh \
    && rosdep install --from-paths src --ignore-src --rosdistro jazzy -yr \
    && rm -rf /var/lib/apt/lists/*

# Build the core packages (this is the slow step you only want to do once!)
RUN . /opt/ros/jazzy/setup.sh \
    && colcon build \
        --merge-install \
        --packages-up-to intrinsic_sdk_ros snapshot_interfaces rmw_zenoh_cpp \
        --cmake-args -DCMAKE_BUILD_TYPE=Release
