# Dockerfile.orbbec_underlay
FROM intrinsic-dev-core-underlay:latest AS underlay

ADD src/OrbbecSDK /opt/ros/underlay/src/OrbbecSDK
ADD src/OrbbecSDK_ROS2 /opt/ros/underlay/src/OrbbecSDK_ROS2

# Compile the Orbbec SDKs into the underlay
RUN . /opt/ros/jazzy/setup.sh \
    && cd /opt/ros/underlay \
    && colcon build \
      --merge-install \
      --executor sequential \
      --cmake-args -DOB_BUILD_USB_PAL=OFF -DOB_BUILD_GMSL_PAL=OFF -DCMAKE_BUILD_TYPE=Release \
    && rm -rf /opt/ros/underlay/build /opt/ros/underlay/log /opt/ros/underlay/src /root/.cache
