# ci_scripts/Dockerfile.luxonis_underlay
FROM ghcr.io/intrinsic-dev/core-underlay:latest AS underlay

RUN apt-get update \
    && apt-get install -y \
        build-essential \
        ninja-build \
        ca-certificates \
        xz-utils \
        wget \
        python3-protobuf \
        libopencv-dev \
        nlohmann-json3-dev \
        ros-jazzy-tf2-ros \
        ros-jazzy-tf2-geometry-msgs \
        libgl1-mesa-dev \
        ros-jazzy-cv-bridge \
        ros-jazzy-backward-ros \
        ros-jazzy-camera-info-manager \
        ros-jazzy-image-transport \
        ros-jazzy-image-publisher \
        ros-jazzy-tf2-eigen \
        ros-jazzy-tf2-sensor-msgs \
        ros-jazzy-diagnostic-updater \
        curl zip unzip tar libusb-1.0-0-dev \
        ros-jazzy-vision-msgs \
        ros-jazzy-ffmpeg-image-transport-msgs \
    && rm -rf /var/lib/apt/lists/*

ADD src/depthai-core /opt/ros/underlay/src/depthai-core
ADD src/depthai-ros /opt/ros/underlay/src/depthai-ros

# Compile the Luxonis SDKs into the underlay
RUN . /opt/ros/jazzy/setup.sh \
    && cd /opt/ros/underlay \
    && colcon build \
      --event-handlers=console_direct+ \
      --merge-install \
      --executor sequential \
      --cmake-args -DBUILD_SHARED_LIBS=ON -DDEPTHAI_BOOTSTRAP_VCPKG=ON \
    && rm -rf /opt/ros/underlay/build /opt/ros/underlay/log /opt/ros/underlay/src /root/.cache