# Build up the service with these stages:
#   - base (ros:jazzy + settings) ->
#   - underlay (dependencies) ->
#   - overlay (user code) ->
#   - result (base + copied install folder of underlay and overlay)

# base stage: ros:jazzy + configs
FROM ros:jazzy-ros-core AS base

ARG ENSENSO_VERSION=4.3.905

WORKDIR /opt/ros/underlay

ENV ROS_DISTRO=jazzy
ENV ROS_HOME=/tmp
ENV RMW_IMPLEMENTATION=rmw_zenoh_cpp

# underlay stage: base + dependencies built
FROM base AS underlay

ADD src/flowstate-ros-camera-drivers/flowstate_ensenso /opt/ros/underlay/src/flowstate-ros-camera-drivers/flowstate_ensenso
ADD src/flowstate-ros-camera-drivers/flowstate_common /opt/ros/underlay/src/flowstate-ros-camera-drivers/flowstate_common
ADD src/sdk-ros /opt/ros/underlay/src/sdk-ros

# Install build dependencies.
RUN apt-get update && \
    apt-get install -y \
    python3-rosdep \
    python3-colcon-common-extensions \
    ros-jazzy-ament-cmake-vendor-package \
    git \
    wget \
    python3-pip

RUN rosdep init || true && \
    rosdep update

RUN wget -O ensenso.deb "https://download.optonic.com/s/ensensosdk/download?files=ensenso-sdk-${ENSENSO_VERSION}-x64.deb" && \
    apt-get install -y ./ensenso.deb && \
    rm ensenso.deb

ENV ENSENSO_INSTALL=/opt/ensenso

RUN cd /opt/ros/underlay/src/ && \
    git clone https://github.com/ensenso/ros_driver && \
    cd ros_driver && \
    # Run the prepare script for ROS2 for Ensenso
    export ROS_VERSION=2 && ./.github/scripts/prepare_ros2_build.sh

RUN pip3 install transforms3d --break-system-packages || true

RUN cd /opt/ros/underlay/src/ && \
    git clone https://github.com/codebot/rmw_zenoh -b morganquigley/jazzy_with_old_attachment_metadata_format

RUN cd /opt/ros/underlay/src/rmw_zenoh && \
    git checkout 05cdda05a7c5e7c2871e6d85bfc9411546a529c4

RUN cd /opt/ros/underlay && \
    . /opt/ros/jazzy/setup.sh && \
    rosdep install --from-paths src --ignore-src --rosdistro jazzy -y --skip-keys "snapshot_interfaces OrbbecSDK roscpp message_runtime catkin tf rostest nodelet message_generation actionlib rospy roslint ensenso_camera" \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /root/.ros/rosdep

# install rmw_zenoh
RUN . /opt/ros/jazzy/setup.sh \
    && colcon build \
        --event-handlers=console_direct+ \
        --merge-install \
        --packages-up-to=rmw_zenoh_cpp

RUN . /opt/ros/jazzy/setup.sh && \
    . /opt/ros/underlay/install/setup.sh && \
    cd /opt/ros/underlay && \
    colcon build \
        --event-handlers=console_direct+ \
        --merge-install \
        --packages-up-to flowstate_camera_common ensenso_camera \
        --cmake-args -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-Wno-error=invalid-constexpr -Wno-invalid-constexpr -Wno-deprecated-declarations"

RUN echo "Copying missing Ensenso wrapper headers..." && \
    cp -r /opt/ros/underlay/src/ros_driver/ensenso_camera2/include/* /opt/ros/underlay/install/include/

RUN echo "Searching for and copying vendored libprotobuf..." && \
    find /opt/ros/underlay/build -name "libprotobuf.so.29.0.0" -exec cp {} /opt/ros/underlay/install/lib/ \; || true

RUN echo "Searching for and copying vendored absl libraries..." && \
    find /opt/ros/underlay/build/abseil_cpp_vendor -name "libabsl*.so*" -exec cp -d {} /opt/ros/underlay/install/lib/ \; || true

RUN rm -rf /opt/ros/underlay/build /opt/ros/underlay/log

# overlay stage: underlay + service code built
FROM underlay AS overlay

ARG SERVICE_PACKAGE=flowstate_ensenso
ARG DEPENDENCIES

RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get update \
    && apt install -y --fix-missing python3-protobuf libopencv-dev nlohmann-json3-dev ${DEPENDENCIES} \
    && rm -rf /var/lib/apt/lists/*

ADD src /opt/ros/overlay/src

RUN . /opt/ros/jazzy/setup.sh \
    && . /opt/ros/underlay/install/setup.sh \
    && cd /opt/ros/overlay \
    && colcon build \
      --event-handlers=console_direct+ \
      --merge-install \
      --packages-above-and-dependencies=${SERVICE_PACKAGE} \
      --cmake-args -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-Wno-error=invalid-constexpr -Wno-invalid-constexpr -Wno-deprecated-declarations" \
    && rm -rf /opt/ros/overlay/build /opt/ros/overlay/log

# Clean up source code and caches
RUN rm -rf /opt/ros/underlay/src \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* \
    && rm -rf /root/.cache

# result stage: base + copied install folders from the overlay + service setup
FROM base

ARG SERVICE_PACKAGE=flowstate_ensenso
ARG SERVICE_NAME=ensenso_driver
ARG DEPENDENCIES

RUN apt-get update \
    && apt-get install -y --fix-missing \
    ros-jazzy-image-transport \
    ros-jazzy-image-transport-plugins \
    ros-jazzy-std-srvs \
    ros-jazzy-cv-bridge \
    ros-jazzy-diagnostic-msgs \
    ros-jazzy-image-geometry \
    ros-jazzy-pcl-conversions \
    ros-jazzy-pcl-ros \
    ros-jazzy-rclcpp-action \
    ros-jazzy-rclcpp-components \
    ros-jazzy-tf2 \
    ros-jazzy-tf2-geometry-msgs \
    ros-jazzy-tf2-ros \
    ros-jazzy-visualization-msgs \
    wget && \
    wget -O ensenso.deb "https://download.optonic.com/s/ensensosdk/download?files=ensenso-sdk-${ENSENSO_VERSION}-x64.deb" && \
    apt-get install -y ./ensenso.deb && \
    rm ensenso.deb && \
    rm -rf /var/lib/apt/lists/*

COPY --from=overlay /opt/ros/underlay/install /opt/ros/underlay/install
COPY --from=overlay /opt/ros/overlay/install /opt/ros/overlay/install

RUN echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf && ldconfig

RUN cp /opt/ros/overlay/install/share/${SERVICE_PACKAGE}/service_manifest.binarypb /service_manifest.binarypb \
    && cp /opt/ros/overlay/install/share/${SERVICE_PACKAGE}/default_config.binarypb /default_config.binarypb \
    && cp /opt/ros/overlay/install/share/${SERVICE_PACKAGE}/ensenso_driver_protos.desc /parameter-descriptor-set.proto.bin \
    && sed --in-place \
        --expression '$isource "/opt/ros/overlay/install/setup.bash"' \
        /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]

ENV SERVICE_PACKAGE=${SERVICE_PACKAGE}
ENV SERVICE_NAME=${SERVICE_NAME}
ENV RUST_LOG=info

ENV ZENOH_CONFIG_OVERRIDE='connect/endpoints=["tcp/localhost:17447"]'

CMD exec /opt/ros/overlay/install/lib/${SERVICE_PACKAGE}/flowstate_service
