# Build up the service with these stages:
#   - base (ros:jazzy + settings) ->
#   - underlay (dependencies) ->
#   - overlay (user code) ->
#   - result (base + copied install folder of underlay and overlay)

# base stage: ros:jazzy + configs
FROM ros:jazzy-ros-core AS base

WORKDIR /opt/ros/underlay

ENV ROS_HOME=/tmp
ENV RMW_IMPLEMENTATION=rmw_zenoh_cpp

FROM ghcr.io/intrinsic-dev/core-underlay:latest AS underlay

# overlay stage: underlay + service code built
FROM underlay AS overlay

ARG SERVICE_PACKAGE
ARG DEPENDENCIES

RUN apt-get update \
    && apt install -y python3-protobuf libopencv-dev nlohmann-json3-dev ${DEPENDENCIES} ros-jazzy-tf2-ros ros-jazzy-tf2-geometry-msgs libgl1-mesa-dev ros-jazzy-cv-bridge ros-jazzy-backward-ros ros-jazzy-camera-info-manager ros-jazzy-image-transport ros-jazzy-image-publisher ros-jazzy-tf2-eigen ros-jazzy-tf2-sensor-msgs ros-jazzy-diagnostic-updater \
    && rm -rf /var/lib/apt/lists/*

ADD src/flowstate-ros-camera-drivers /opt/ros/overlay/src/flowstate-ros-camera-drivers
ADD src/OrbbecSDK /opt/ros/overlay/src/OrbbecSDK
ADD src/OrbbecSDK_ROS2 /opt/ros/overlay/src/OrbbecSDK_ROS2

# skip a few packages that are already built, and are somewhat slow to process
RUN . /opt/ros/jazzy/setup.sh \
    && . /opt/ros/underlay/install/setup.sh \
    && cd /opt/ros/overlay \
    && colcon build \
      --merge-install \
      --executor sequential \
      --packages-up-to=${SERVICE_PACKAGE} \
      --packages-skip \
        intrinsic_sdk \
        intrinsic_sdk_ros \
        intrinsic_sdk_cmake \
        gz_msgs_vendor \
        grpc_vendor \
        abseil_cpp_vendor \
        re2_vendor \
        rmw_zenoh_cpp \
        ortools_vendor \
        eigen_vendor \
        gz_make_vendor \
        gz_utils_vendor \
        intrinsic_pybind11_vendor \
        gz_math_vendor \
        prometheus_cpp_vendor \
        bazelisk_vendor \
        flatbuffers_vendor \
        opencensus_cpp_vendor \
      --cmake-args -DOB_BUILD_USB_PAL=OFF -DOB_BUILD_GMSL_PAL=OFF -DCMAKE_BUILD_TYPE=Release

# result stage: base + copied install folders from the overlay + service setup
FROM base

ARG SERVICE_PACKAGE
ARG SERVICE_NAME
ARG DEPENDENCIES

RUN apt-get update \
    && apt-get install -y python3-protobuf libopencv-core-dev ${DEPENDENCIES} iputils-ping net-tools ros-jazzy-tf2-ros ros-jazzy-tf2-geometry-msgs ros-jazzy-cv-bridge ros-jazzy-backward-ros ros-jazzy-camera-info-manager ros-jazzy-image-transport ros-jazzy-image-publisher ros-jazzy-tf2-eigen ros-jazzy-tf2-sensor-msgs ros-jazzy-diagnostic-updater \
    && rm -rf /var/lib/apt/lists/*

COPY --from=overlay /opt/ros/underlay/install /opt/ros/underlay/install
COPY --from=overlay /opt/ros/overlay/install /opt/ros/overlay/install

RUN cp \
        /opt/ros/overlay/install/share/${SERVICE_PACKAGE}/service_manifest.binarypb \
        /service_manifest.binarypb \
    && cp \
        /opt/ros/overlay/install/share/${SERVICE_PACKAGE}/default_config.binarypb \
        /default_config.binarypb \
    && cp \
        /opt/ros/overlay/install/share/${SERVICE_PACKAGE}/${SERVICE_NAME}_protos.desc \
        /parameter-descriptor-set.proto.bin \
    && sed --in-place \
        --expression '$isource "/opt/ros/overlay/install/setup.bash"' \
        /ros_entrypoint.sh

# Build arguments are not substituted in the CMD command and hence we set environment variables
# which can be substituted instead.
ENV SERVICE_PACKAGE=${SERVICE_PACKAGE}
ENV SERVICE_NAME=${SERVICE_NAME}
ENV RUST_LOG=info

# This zenoh_config is the same as the default, other than it connects to the
# kubernetes-provided port which forwards to the zenoh-router:
ENV ZENOH_CONFIG_OVERRIDE='connect/endpoints=["tcp/localhost:17447"]'

CMD exec /opt/ros/overlay/install/lib/${SERVICE_PACKAGE}/flowstate_service
# CMD ["/bin/bash", "-c", "echo 'Sleeping...'; sleep infinity"]
