# Build up the service with these stages:
#   - base (ros:jazzy + settings) ->
#   - underlay (dependencies) ->
#   - overlay (user code) ->
#   - result (base + copied install folder of underlay and overlay)

# base stage: ros:jazzy + configs
FROM ros:jazzy-ros-core AS base

WORKDIR /opt/ros/underlay

ENV ROS_HOME=/tmp
ENV RMW_IMPLEMENTATION=rmw_zenoh_cpp

# underlay stage: base + dependencies built
FROM base AS underlay

RUN . /opt/ros/jazzy/setup.sh \
    && apt-get update \
    && apt install -y clang ros-jazzy-ament-cmake-vendor-package ros-dev-tools \
    && rm -rf /var/lib/apt/lists/*

RUN rosdep init

ADD src/sdk-ros /opt/ros/underlay/src/intrinsic_sdk_ros

# Install a compatible fork of rmw_zenoh
RUN cd /opt/ros/underlay/src/ \
    && git clone https://github.com/codebot/rmw_zenoh -b morganquigley/jazzy_with_old_attachment_metadata_format && cd rmw_zenoh && git checkout 05cdda05a7c5e7c2871e6d85bfc9411546a529c4 && cd ../..

RUN . /opt/ros/jazzy/setup.sh \
    && apt-get update \
    && rosdep update \
    && rosdep install --from-paths src --ignore-src --rosdistro jazzy -yr \
    && rm -rf /var/lib/apt/lists/*

RUN . /opt/ros/jazzy/setup.sh \
    && colcon build \
        --merge-install \
        --packages-up-to intrinsic_sdk_ros snapshot_interfaces \
        --cmake-args -DBUILD_SHARED_LIBS=ON

RUN . /opt/ros/jazzy/setup.sh \
    && colcon build \
        --merge-install \
        --packages-up-to=rmw_zenoh_cpp \
        --cmake-args -DBUILD_SHARED_LIBS=ON

# overlay stage: underlay + service code built
FROM underlay AS overlay

ARG SERVICE_PACKAGE
ARG DEPENDENCIES

RUN apt-get update \
    && apt install -y python3-protobuf libopencv-dev nlohmann-json3-dev ${DEPENDENCIES} ros-jazzy-tf2-ros ros-jazzy-tf2-geometry-msgs libgl1-mesa-dev ros-jazzy-cv-bridge ros-jazzy-backward-ros ros-jazzy-camera-info-manager ros-jazzy-image-transport ros-jazzy-image-publisher ros-jazzy-tf2-eigen ros-jazzy-tf2-sensor-msgs ros-jazzy-diagnostic-updater curl zip unzip tar libusb-1.0-0-dev ros-jazzy-vision-msgs ros-jazzy-ffmpeg-image-transport-msgs \
    && rm -rf /var/lib/apt/lists/*

ADD src/depthai-core /opt/ros/overlay/src/depthai-core
ADD src/depthai-ros /opt/ros/overlay/src/depthai-ros
RUN . /opt/ros/jazzy/setup.sh \
    && . /opt/ros/underlay/install/setup.sh \
    && cd /opt/ros/overlay \
    && colcon build \
      --event-handlers=console_direct+ \
      --merge-install \
      --executor sequential \
      --packages-up-to=depthai_ros_driver \
      --packages-skip intrinsic_sdk intrinsic_sdk_ros intrinsic_sdk_cmake grpc_vendor abseil_cpp_vendor re2_vendor rmw_zenoh_cpp ortools_vendor eigen_vendor \
      --cmake-args -DBUILD_SHARED_LIBS=ON -DDEPTHAI_BOOTSTRAP_VCPKG=ON

ADD src/flowstate-ros-camera-drivers /opt/ros/overlay/src/flowstate-ros-camera-drivers

# skip a few packages that are already built, and are somewhat slow to process
RUN . /opt/ros/jazzy/setup.sh \
    && . /opt/ros/underlay/install/setup.sh \
    && cd /opt/ros/overlay \
    && colcon build \
      --event-handlers=console_direct+ \
      --merge-install \
      --executor sequential \
      --packages-up-to=${SERVICE_PACKAGE} \
      --packages-skip intrinsic_sdk intrinsic_sdk_ros intrinsic_sdk_cmake grpc_vendor abseil_cpp_vendor re2_vendor rmw_zenoh_cpp ortools_vendor eigen_vendor \
      --cmake-args -DBUILD_SHARED_LIBS=ON -DDEPTHAI_BOOTSTRAP_VCPKG=ON

# result stage: base + copied install folders from the overlay + service setup
FROM base

ARG SERVICE_PACKAGE
ARG SERVICE_NAME
ARG DEPENDENCIES

RUN apt-get update \
    && apt-get install -y python3-protobuf libopencv-core-dev ${DEPENDENCIES} iputils-ping net-tools ros-jazzy-tf2-ros ros-jazzy-tf2-geometry-msgs ros-jazzy-cv-bridge ros-jazzy-backward-ros ros-jazzy-camera-info-manager ros-jazzy-image-transport ros-jazzy-image-publisher ros-jazzy-tf2-eigen ros-jazzy-tf2-sensor-msgs ros-jazzy-diagnostic-updater curl zip unzip tar libusb-1.0-0-dev ros-jazzy-vision-msgs ros-jazzy-ffmpeg-image-transport-msgs \
    && rm -rf /var/lib/apt/lists/*

COPY --from=overlay /opt/ros/underlay/install /opt/ros/underlay/install
COPY --from=overlay /opt/ros/overlay/install /opt/ros/overlay/install

RUN cp \
        /opt/ros/overlay/install/share/${SERVICE_PACKAGE}/service_manifest.binarypb \
        /service_manifest.binarypb \
    && cp \
        /opt/ros/overlay/install/share/${SERVICE_PACKAGE}/default_config.binarypb \
        /default_config.binarypb \
    && cp \
        /opt/ros/overlay/install/share/${SERVICE_PACKAGE}/${SERVICE_NAME}_protos.desc \
        /parameter-descriptor-set.proto.bin \
    && sed --in-place \
        --expression '$isource "/opt/ros/overlay/install/setup.bash"' \
        /ros_entrypoint.sh

# Build arguments are not substituted in the CMD command and hence we set environment variables
# which can be substituted instead.
ENV SERVICE_PACKAGE=${SERVICE_PACKAGE}
ENV SERVICE_NAME=${SERVICE_NAME}
ENV RUST_LOG=info

# This zenoh_config is the same as the default, other than it connects to the
# kubernetes-provided port which forwards to the zenoh-router:
ENV ZENOH_CONFIG_OVERRIDE='connect/endpoints=["tcp/localhost:17447"]'

CMD exec /opt/ros/overlay/install/lib/${SERVICE_PACKAGE}/flowstate_service
# CMD ["/bin/bash", "-c", "echo 'Sleeping...'; sleep infinity"]
