# proto-file: google/protobuf/any.proto
# proto-message: Any
[type.googleapis.com/luxonis_driver.LuxonisDriverConfig] {
  # If no addresses are provided, the service will automatically discover
  # and use any Luxonis cameras that it finds.
  # Using only particular IP addresses is not yet implemented.

  # ip_address: "192.168.0.12"
}
