name: Camera Drivers Presubmit

on:
  pull_request:
    branches: [ main, sprivas/simplify-cameradrivers ] # TODO remove sprivas/simplify-cameradrivers before merge
  push:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
    outputs:
      cameras: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            orbbec:
              - 'flowstate_orbbec/**'
              - 'flowstate_common/**'
            luxonis:
              - 'flowstate_luxonis/**'
              - 'flowstate_common/**'
            zivid:
              - 'flowstate_zivid/**'
              - 'flowstate_common/**'

  build-bundle:
    needs: detect-changes
    if: needs.detect-changes.outputs.cameras != '[]'
    name: Build ${{ matrix.camera }} Driver
    runs-on: ubuntu-24.04
    
    strategy:
      fail-fast: false
      matrix:
        camera: ${{ fromJSON(needs.detect-changes.outputs.cameras) }}

    steps:
      - name: Create Workspace Directory
        run: mkdir -p workspace/src
      
      # Need to free space otherwise we run out of it during build
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: false

      - name: Checkout Camera Drivers (This Repo)
        uses: actions/checkout@v4
        with:
          path: workspace/src/flowstate-ros-camera-drivers

      - name: Checkout sdk-ros (Public)
        uses: actions/checkout@v4
        with:
          repository: intrinsic-ai/sdk-ros
          path: workspace/src/sdk-ros

      - name: Clone Vendor Dependencies
        working-directory: workspace/src
        run: |
          if [ "${{ matrix.camera }}" == "orbbec" ]; then
            git clone https://github.com/codebot/OrbbecSDK_v2 OrbbecSDK --branch building_without_usb_on_linux
            git clone https://github.com/codebot/OrbbecSDK_ROS2 --branch use_sdk_from_colcon_build
            
          elif [ "${{ matrix.camera }}" == "luxonis" ]; then
            git clone https://github.com/codebot/depthai-core --branch kilted
            cd depthai-core && git submodule update --init --recursive && cd ..
            git clone https://github.com/codebot/depthai-ros --branch mq/adjust_export_dependencies
            
          elif [ "${{ matrix.camera }}" == "zivid" ]; then
            git clone https://github.com/zivid/zivid-ros.git
          fi

      - name: Build Service Bundle
        working-directory: workspace
        run: |
          chmod +x src/flowstate-ros-camera-drivers/flowstate_${{ matrix.camera }}/flowstate/build_service_bundle.sh
          ./src/flowstate-ros-camera-drivers/flowstate_${{ matrix.camera }}/flowstate/build_service_bundle.sh