name: Camera Drivers Presubmit

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
    outputs:
      cameras: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            orbbec:
              - 'flowstate_orbbec/**'
              - 'flowstate_common/**'
            luxonis:
              - 'flowstate_luxonis/**'
              - 'flowstate_common/**'
            zivid:
              - 'flowstate_zivid/**'
              - 'flowstate_common/**'

  build-bundle:
    needs: detect-changes
    if: needs.detect-changes.outputs.cameras != '[]'
    name: Build ${{ matrix.camera }} Driver
    runs-on: ubuntu-24.04
    
    strategy:
      fail-fast: false
      matrix:
        camera: ${{ fromJSON(needs.detect-changes.outputs.cameras) }}

    steps:
      - name: Create Workspace Directory
        run: mkdir -p workspace/src
      
      # Need to free space otherwise we run out of it during build
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Checkout Camera Drivers (This Repo)
        uses: actions/checkout@v4
        with:
          path: workspace/src/flowstate-ros-camera-drivers

      - name: Checkout sdk-ros (Public)
        uses: actions/checkout@v4
        with:
          repository: intrinsic-ai/sdk-ros
          path: workspace/src/sdk-ros

      - name: Clone Vendor Dependencies
        working-directory: workspace/src
        run: |
          if [ "${{ matrix.camera }}" == "zivid" ]; then
            git clone https://github.com/zivid/zivid-ros.git
          fi
      - name: Prune Docker
        run: docker system prune -af
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Service Bundle
        working-directory: workspace
        run: |
          chmod +x src/flowstate-ros-camera-drivers/ci_scripts/test_ci_build.sh
          # Set the exact service name based on the camera type
          if [ "${{ matrix.camera }}" == "orbbec" ]; then
            TARGET_SERVICE="orbbec_gemini_driver"
          else
            TARGET_SERVICE="${{ matrix.camera }}_driver"
          fi
          ./src/flowstate-ros-camera-drivers/ci_scripts/test_ci_build.sh $TARGET_SERVICE flowstate_${{ matrix.camera }}