# Dockerfile.zivid_underlay
FROM nvidia/cuda:12.5.1-base-ubuntu24.04 AS base

ARG ZIVID_VERSION=2.17.0+5fc9f05e-1

# Install ROS Jazzy
RUN apt-get update && apt-get install -y curl gnupg2 lsb-release && rm -rf /var/lib/apt/lists/*
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
RUN apt-get clean && apt-get update && apt-get install -y --fix-missing ros-jazzy-ros-base && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/ros/underlay
ENV ROS_DISTRO=jazzy
ENV ROS_HOME=/tmp
ENV RMW_IMPLEMENTATION=rmw_zenoh_cpp

FROM base AS underlay
ARG ZIVID_VERSION

# Copy source code needed for dependencies
ADD src/zivid-ros /opt/ros/underlay/src/zivid-ros
ADD src/flowstate-ros-camera-drivers /opt/ros/underlay/src/flowstate-ros-camera-drivers
ADD src/sdk-ros /opt/ros/underlay/src/sdk-ros

# Install build dependencies
RUN . /opt/ros/jazzy/setup.sh && \
    apt-get update && \
    apt-get install -y ocl-icd-libopencl1 gcc g++ clinfo python3-rosdep python3-colcon-common-extensions ros-jazzy-ament-cmake-vendor-package valgrind ninja-build && \
    rosdep init && rosdep update && \
    rosdep install --from-paths /opt/ros/underlay/src --ignore-src --rosdistro jazzy -y --skip-keys "snapshot_interfaces OrbbecSDK" && \
    colcon build --continue-on-error --merge-install --packages-up-to intrinsic_sdk --parallel-workers 2 --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF && \
    find /opt/ros/underlay/build -name "libprotobuf.so.29.0.0" -exec cp {} /opt/ros/underlay/install/lib/ \; && \
    find /opt/ros/underlay/build/abseil_cpp_vendor -name "libabsl*.so*" -exec cp -d {} /opt/ros/underlay/install/lib/ \; && \
    rm -rf /opt/ros/underlay/build /opt/ros/underlay/log /var/lib/apt/lists/* /root/.ros/rosdep

RUN mkdir -p /etc/OpenCL/vendors && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility

# Install Zivid deb packages
RUN apt-get update && apt-get install -y wget && \
    wget https://downloads.zivid.com/sdk/releases/${ZIVID_VERSION}/u24/amd64/zivid_${ZIVID_VERSION}_amd64.deb \
         https://downloads.zivid.com/sdk/releases/${ZIVID_VERSION}/u24/amd64/zivid-studio_${ZIVID_VERSION}_amd64.deb \
         https://downloads.zivid.com/sdk/releases/${ZIVID_VERSION}/u24/amd64/zivid-tools_${ZIVID_VERSION}_amd64.deb \
         https://downloads.zivid.com/sdk/releases/${ZIVID_VERSION}/u24/amd64/zivid-genicam_${ZIVID_VERSION}_amd64.deb && \
    apt-get install -y ./*.deb && rm ./*.deb && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

# Install rmw_zenoh
RUN cd /opt/ros/underlay/src/ && \
    git clone https://github.com/codebot/rmw_zenoh -b morganquigley/jazzy_with_old_attachment_metadata_format && \
    cd rmw_zenoh && git checkout 05cdda05a7c5e7c2871e6d85bfc9411546a529c4 && cd ../.. && \
    . /opt/ros/jazzy/setup.sh && apt-get update && rosdep update && \
    rosdep install --from-paths src --ignore-src --rosdistro jazzy -yr && \
    colcon build --merge-install --packages-up-to=rmw_zenoh_cpp --parallel-workers 2 --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF && \
    rm -rf /opt/ros/underlay/build /opt/ros/underlay/log /var/lib/apt/lists/*